Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.PaperTiger: true
    Ui:
      resources:
        javascript:
          '@sitegeist/papertiger-editors':
            resource: 'resource://Sitegeist.PaperTiger/Public/Neos.Ui/Plugin.js'
