Sitegeist:
  PaperTiger:
    rendering:
      classes:
        form: ''

        container: ''
        label: ''
        error: 'error'
        submit: ''

        field:
          dropdown: ''
          checkbox: ''
          radiobutton: ''
          singleLineText: ''
          multiLineText: ''
          date: ''
          email: ''
          tel: ''
          number: ''
          range: ''
          upload: ''


Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.PaperTiger: true

    nodeTypes:
      groups:
        'form.elements':
          label: 'Form Elements'
          collapsed: false
        'form.special':
          label: 'Special Form Elements'
          collapsed: false

    Ui:
      resources:
        javascript:
          '@sitegeist/papertiger-editors':
            resource: 'resource://Sitegeist.PaperTiger/Public/Neos.Ui/Plugin.js'


