Neos:
  Fusion:
    defaultContext:
      PaperTiger: "Sitegeist\\PaperTiger\\Helper\\PaperTigerHelper"
  Neos:
    fusion:
      autoInclude:
        Sitegeist.PaperTiger: true

    nodeTypes:
      groups:
        'form.elements':
          label: 'Sitegeist.PaperTiger:Main:nodeTypes.groups.form.elements'
          collapsed: false
        'form.special':
          label: 'Sitegeist.PaperTiger:Main:nodeTypes.groups.form.special'
          collapsed: false

    userInterface:
      translation:
        autoInclude:
          Sitegeist.PaperTiger:
            - Main
            - 'NodeTypes/*'

    Ui:
      resources:
        javascript:
          '@sitegeist/papertiger-editors':
            resource: 'resource://Sitegeist.PaperTiger/Public/Neos.Ui/Plugin.js'


